name: mercadinho
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  add_to_cart_animation: ^2.0.4
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.6
  intl: ^0.19.0
  mask_text_input_formatter: ^2.9.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fruits/
    - assets/app_images/
